version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - DISCORD_WEBHOOK_URL=YOUR_DISCORD_WEBHOOK_URL
      - CHECK_INTERVAL=1800
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
