version: '3.8'

services:
  github-release-notifier:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CHECK_INTERVAL: 7200
      DISCORD_WEBHOOK_URL: YOUR_DISCORD_WEBHOOK_URL
      GITHUB_TOKEN: YOUR_GITHUB_TOKEN
    volumes:
      - ./repositories.txt:/app/repositories.txt
    restart: always

  web-gui:
    image: nginx:alpine
    volumes:
      - ./web-gui:/usr/share/nginx/html
    ports:
      - "8080:80"
